name: MC-GANS
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - scipy
  - scikit-learn
  - joblib
  - pandas
  - matplotlib
  - seaborn
  - tqdm
  - networkx
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1 # 确保 CUDA 版本匹配
  - graphviz
  - sympy
  - mpmath
  - python-graphviz
  - triton
  - typing-extensions
  - pip
  - pip:
    - filelock==3.16.1
    - fsspec==2024.9.0
    - jinja2==3.1.4
    - markupsafe==3.0.1
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.6.77
    - nvidia-nvtx-cu12==12.1.105